server:
  port: 3100
spring:
  application:
    name: client-consumer-ribbon
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    metadata-map:
      cluster: main
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://json:zhangbo123@localhost:8761/eureka/
  